### PR TITLE
Article overhaul

### PR DESCRIPTION
**Pull request by XhmikosR**
http://xhmikosr.github.io/nfe/

http://gtmetrix.com/compare/WTK64p39/ftJ1zSRv

It's a little slower due to highlighting and so many `<pre>` stuff, but I guess the improved look and functionality justifies that.

One potential improvement would be to add the affix plugin, but not sure if I'll ever get to do that.

### CODE REVIEW

**Comment by kangax** [comment]
@XhmikosR this is amazing... thanks so much for doing all this! Looks better for sure.

**Comment by XhmikosR** [comment]
No problem, glad I could help :)

PS. I'd like to see details about `!(function){})()` or `+` etc when you have some time.

**Comment by kangax** [comment]
Hm, not sure NFE article is the best place to explain those...

`!(function(){})()` is just one way to "construct" anonymous function expression. Since we can't just write `function(){}()` — parser gets confused about it — we have to somehow let it know that this is an expression.

Traditionally, it's been done either via `(function(){})()` or `(function(){}())` — basically using parens (`(` and `)`) to wrap around, enforcing "expression" context.

Later, people started doing this via single operators like `!` or `+`, etc. — `!function(){}()`, `+function(){}()`. It's just another way to "force" expression context, without using `(` and `)`.

I've been using parens for many years and still do.

**Comment by XhmikosR** [comment]
Thanks for your time explaining this! I still believe it can this can be included in the article, though. But maybe it's just me.

Thanks again!

**Pull request merged**
